[project]
name = "tutorgebra"
version = "0.1.0"
description = "Your automated interactive geometry tutor."
readme = "README.md"
authors = [
    { name = "ANGELUSD11", email = "angelleonardohern3@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "gTTS",
    "google-genai",
    "edge-tts",
]

[project.scripts]
tutorgebra = "tutorgebra:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
